Project puyopuyo 1
xfrnk2/puyopuyo pull request #1
Opened 2021-02-23 11:47 UTC by xfrnk2

Project puyopuyo 1

2021-02-24 03:30 UTC, zrma approved these changes
조금 보강 수정만 하고 바로 merge 하시죠 ㄱㄱㄱ

2021-02-24 03:30 UTC, zrma commented on README.md
> +python src/main.py
의존성이 있기 때문에 이 문구만으로는 실행 할 수 없습니다.\
이 부분의 보강이 필요한 것 같아요.

2021-02-24 03:30 UTC, zrma commented on src/event.py
> +    @staticmethod
[code reformatting](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html) 해 주세요,

2021-02-24 03:30 UTC, zrma commented on src/main.py
> +    pass
여기도 [code reformatting](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html) 해 주세요,

2021-02-24 03:30 UTC, zrma commented on tests/event_test.py
> +        pyautogui.press(case.key)
👍

2021-03-04 13:04 UTC, zrma requested changes

2021-03-04 13:04 UTC, zrma commented on tests/renderer_test.py
> +from src.renderer import Renderer
@xfrnk2 

뭔가 테스트 코드는 추가되었는데, 그 구현체인 renderer 파일은 보이지 않네요?\
누락 되었나봐요.

2021-03-04 16:47 UTC, zrma requested changes

2021-03-04 16:47 UTC, zrma commented on README.md
> +pip install pynput
이게 단순하게 여기서 직접 `pip install pynput`을 명시하기보다는

지금 해당 프로젝트의 상황이 [setup.py](https://github.com/xfrnk2/puyopuyo/blob/09967955e2e49b6ce6a82bacf4753c955d65660b/setup.py)에 의존 관계를 서술하고 있고\
[Makefile](https://github.com/xfrnk2/puyopuyo/blob/09967955e2e49b6ce6a82bacf4753c955d65660b/Makefile#L25)에서 [가상환경](https://docs.python.org/ko/3/tutorial/venv.html)을 생성하고 [의존성이 있는 모듈을 설치](https://docs.python.org/ko/3/installing/index.html)하는 과정을 거치고 있으니까 

이 부분을 활용하거나\
아니면 위의 이런 부분들을 다 정리하고 `pynput`을 [requirements.txt](https://github.com/xfrnk2/puyopuyo/blob/09967955e2e49b6ce6a82bacf4753c955d65660b/requirements.txt)에서 명시적으로 설치하도록 하고 [가상환경에서 requirements.txt를 설치하는](https://docs.python.org/ko/3/tutorial/venv.html) 내용을 다루는 편이 더 나을 것 같습니다.

2021-03-04 16:47 UTC, zrma commented on src/renderer.py
> +    def renderable(self) -> bool:
이 함수는 뭘 하려는 함수일까요?\
직관적으로 드러나지 않으니 적절한 명명이 필요하거나 주석을 보강해야 할 것 같아요.

그리고 [tick[(https://en.wikipedia.org/wiki/Tick_(disambiguation))은 시간이 아니라 시각, 특히 어떤 회차를 표현하기 위한 것 같습니다.\
elapsted_time는 어떤 시간(간격)에 대한 표현이고요.

이 부분을 먼저, 이 함수가 무엇을 하고 싶은지를 명확히 정리하고 나면\
어떤 변수가 필요하고 무슨 연산을 해야 할지가 정해질 것 같아요.

2021-03-04 16:47 UTC, zrma commented on tests/renderer_test.py
> +def test_renderable1(Case1):
Renderer 쪽의 주석이 더 보강 되거나,\
아니면 이 테스트 코드가 무엇을 의도하고 작성한 것인지가 보강 되어야 할 것 같습니다.

지금 작성 된 코드들만 봐서는\
저로서는 이 코드가 왜 필요한지, 무슨 역할을 하는지 파악하거나 \
작성 의도를 이해할 수 없을 것 같아요.

2021-03-06 13:14 UTC, xfrnk2 commented on tests/renderer_test.py
> +def test_renderable1(Case1):
@zrma 감사합니다 (_ _)

2021-03-17 09:53 UTC, zrma requested changes
이전의 리뷰 내역에 대한 변경이나 반영, 그리고 해당 Pull Request를 병합 처리 하지 않고\
다른 주제로 넘어가서 변경을 키우는 것은 좋은 전략이 아닌 것 같습니다.

하나의 PR에서 다루는 범위가 너무 커져서 제대로 코드를 확인하기도 힘들어집니다.

하나의 PR은 하나의 주제에 대한 변경만 있으면 좋겠어요.\
코드의 가독성과 집중도가 떨어지지 않는 규모의 변경이면 좋겠습니다.

2021-03-17 09:53 UTC, zrma commented on tests/puyo_test.py
> +        assert puyo.falling(time) == expected
[formatting](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html 한 번 해야 할 것 같아요.

2021-03-17 09:53 UTC, zrma commented on tests/puyo_test.py
> +LOGIC = Logic()
각 개별 테스트 내부에서가 아니라 해당 파일의 전역 공간에 이렇게 생성하신 이유가 있나요?

2021-03-17 13:32 UTC, xfrnk2 commented on tests/puyo_test.py
> +        assert puyo.falling(time) == expected
@zrma 넵 알려주셔서 감사합니다. 빠르게 Pull Request를 병합하고 다른 주제에 대한 커밋을 계속 해갈게요.

2021-03-17 13:37 UTC, xfrnk2 commented on tests/puyo_test.py
> +LOGIC = Logic()
@zrma 각 테스트별로 사용 용도가 바뀌지 않아 전역 공간에 생성했는데 이상한 모양이 될 수 있는건 미처 생각하지 못했던 것 같아요. 테스트 내부에서 생성하도록 바꾸어 놓을게요 :)

2021-03-17 13:42 UTC, xfrnk2 commented on README.md
> +pip install pynput
말씀해주신 내용 참고해서 수정 해 보았어요
[README.md 수정 : Make를 requirement로 추가, Test 카테고리 작성](https://github.com/xfrnk2/puyopuyo/pull/1/commits/9bfd9bdabf1f84a0f22e21f2ad9182339aea11bb)
[setup.py : requirement로서 pynput 추가](https://github.com/xfrnk2/puyopuyo/pull/1/commits/0b3b8e209392e845adb780339c9b2a5eecc3a89a)

2021-03-17 13:52 UTC, xfrnk2 commented on src/renderer.py
> +    def renderable(self) -> bool:
@zrma
 [renderer_test.py : 이전과 다른 형태로 테스트 케이스 작성 & renderer.py : 출력을 담당하는 class를 이전과 다른 형태로 작성](https://github.com/xfrnk2/puyopuyo/pull/1/commits/e7aa49f006a673181e77d05f94c98a15bbac8557)

말씀해주신 내용대로 renderable()함수(와 그 테스트 코드)를 보니 직관적이지 않고 적절하지 않은 함수인 것 같아서...
이 부분(언급된 함수 & 함수에 대한 테스트)를 날리기로 생각한 뒤, 
작은 단위의 함수에서부터 다시 시작하는 방향으로 했었는데 혼선을 드려 죄송해요.

함수 제거에 대한 커밋을 마지막으로 남기고, Pull Request 병합한 후 말씀하신 내용 반영 및 진행해 나갈게요.

2021-03-17 14:07 UTC, merged

2021-03-17 14:45 UTC, zrma commented
이미 코드를 병합하셨는데 

여담이지만 [git rebase](https://git-scm.com/docs/git-rebase)를 통해 [semi-linear하게](https://www.bitsnbites.eu/a-tidy-linear-git-history/) 히스토리를 정리하거나\
[커밋 순서를 바꾸거나, 내용을 수정하거나 합치거나 쪼갤 수](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) 있습니다.

다음에는 병합 전에 이렇게 커밋 히스토리를 정돈해서 force push해 보면 어떨까요?

2021-03-17 14:55 UTC, xfrnk2 commented
@zrma 감사합니다. 변경 내역을 따로 빼놨다가 커밋 순서를 바꿀걸 그랬네요(...). 다음에는 꼭 따라보도록 하겠습니다!